from __future__ import annotations

import hashlib
import hmac
import json
import logging
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional

import httpx
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse

from .config import load_settings
from .github import GitHubClient
from .risk import RiskResult, compute_risk

logger = logging.getLogger("pr_risk_bot")


# ---------------------------------------------------------------------------
# App lifespan – initialise clients once, clean up on shutdown
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = load_settings()
    app.state.settings = settings
    app.state.gh = GitHubClient(
        token=settings.github_token,
        base_url=settings.base_url,
    )
    logger.info("pr-risk-bot started (base_url=%s)", settings.base_url)
    yield
    await app.state.gh.aclose()
    logger.info("pr-risk-bot shut down")


app = FastAPI(title="PR Risk Bot", version="1.0.0", lifespan=lifespan)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def verify_signature(body: bytes, signature_header: Optional[str], secret: str) -> None:
    """Validate the GitHub HMAC-SHA256 webhook signature."""
    if not signature_header or not signature_header.startswith("sha256="):
        raise HTTPException(status_code=401, detail="Missing or invalid signature header")
    their_sig = signature_header.split("=", 1)[1].strip()
    our_sig = hmac.new(secret.encode(), msg=body, digestmod=hashlib.sha256).hexdigest()
    if not hmac.compare_digest(our_sig, their_sig):
        raise HTTPException(status_code=401, detail="Signature mismatch")


def make_comment(pr: Dict[str, Any], result: RiskResult) -> str:
    """Render the PR triage summary as a Markdown comment."""
    url    = pr.get("html_url", "")
    title  = pr.get("title", "")
    number = pr.get("number", "")
    user   = (pr.get("user") or {}).get("login", "unknown")

    lines: List[str] = [
        "## PR Triage Summary",
        f"- PR: [{title} #{number}]({url})",
        f"- Author: `{user}`",
        f"- Risk: **{result.score_10}/10 ({result.level})** — confidence: **{result.confidence}**",
        f"- Summary: {result.changed_files} files, {result.additions}+/{result.deletions}-",
        "",
        "### What changed (impact map)",
    ]

    lines += [f"- {item}" for item in result.impact_map[:8]] or ["- (Could not infer impact map)"]
    lines += [
        "",
        "### Risk drivers",
    ]
    lines += [f"{i}. {d}" for i, d in enumerate(result.risk_drivers[:6], 1)] or ["1. (No strong drivers detected)"]
    lines += [
        "",
        "### Suggested review focus",
    ]
    lines += [f"- {item}" for item in result.review_focus[:5]] or ["- (No specific review focus detected)"]
    lines += [
        "",
        "### Operational notes (if applicable)",
    ]
    lines += [f"- {n}" for n in result.operational_notes[:5]] or ["- None"]
    lines += [
        "",
        "> Generated by pr-risk-bot (heuristics-first).",
    ]

    return "\n".join(lines)


BOT_SIGNATURE = "<!-- pr-risk-bot -->"


def make_comment_with_signature(pr: Dict[str, Any], result: RiskResult) -> str:
    """Append a hidden HTML comment so we can find and update existing bot comments."""
    return make_comment(pr, result) + f"\n{BOT_SIGNATURE}"


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.post("/webhook/github")
async def github_webhook(
    request: Request,
    x_hub_signature_256: Optional[str] = Header(default=None),
    x_github_event: Optional[str] = Header(default=None),
) -> JSONResponse:
    body = await request.body()
    settings = request.app.state.settings
    gh: GitHubClient = request.app.state.gh

    verify_signature(body, x_hub_signature_256, settings.webhook_secret)

    try:
        payload: Dict[str, Any] = json.loads(body)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid JSON payload")

    if x_github_event != "pull_request":
        return JSONResponse({"ok": True, "ignored": True, "reason": "not pull_request"})

    action = payload.get("action")
    if action not in {"opened", "reopened", "synchronize"}:
        return JSONResponse({"ok": True, "ignored": True, "reason": f"action={action}"})

    pr      = payload.get("pull_request") or {}
    repo    = payload.get("repository") or {}
    owner   = (repo.get("owner") or {}).get("login")
    repo_name = repo.get("name")
    pr_number = pr.get("number")

    if not (owner and repo_name and pr_number):
        raise HTTPException(status_code=400, detail="Missing repo/PR info in payload")

    logger.info("Processing PR #%s in %s/%s (action=%s)", pr_number, owner, repo_name, action)

    pr_full = await gh.get_pr(owner, repo_name, int(pr_number))
    files   = await gh.list_pr_files(owner, repo_name, int(pr_number))

    result  = compute_risk(files, pr_full)
    comment = make_comment_with_signature(pr_full, result)

    # Idempotency: update existing bot comment instead of posting a new one
    existing_id = await gh.find_bot_comment(owner, repo_name, int(pr_number), BOT_SIGNATURE)
    if existing_id:
        await gh.update_issue_comment(owner, repo_name, existing_id, comment)
        logger.info("Updated existing comment %s on PR #%s (risk=%s)", existing_id, pr_number, result.level)
    else:
        await gh.create_issue_comment(owner, repo_name, int(pr_number), comment)
        logger.info("Posted new comment on PR #%s (risk=%s)", pr_number, result.level)

    return JSONResponse({"ok": True, "posted": True, "risk": result.level, "score": result.score_10})


@app.get("/health")
async def health() -> Dict[str, Any]:
    return {"ok": True}
